<?php
include_once "config.php";

	function mailForNotifySongsUpload($musician_name, $to, $notifyUserName, $share_song_id)
	{
		global $notify_user_alert;
		$headers = "From:DMMCompany Alerts <".$notify_user_alert.">\r\n";
		$headers .= "Content-type: text/html; charset=iso-8859-1" . "\r\n";
		$message = messageForNotifySongsUpload($musician_name, $notifyUserName, $share_song_id);
		$subject = 'DMMCompany New Music Alerts';
		mail($to,$subject,$message,$headers);
	}

	function messageForNotifySongsUpload($musician_name, $notifyUserName, $share_song_id)
	{
		//$message = "Dear clinic,"."<br/>";
		//$message .= "Your appointment has been booked for ".$date." in ".$clinicName." at ".$startTime.". To cancel logon to www.weqaya.ae";
		//$sharesongurl = SHARE_ROOT_URL.'/index.php?tmp_share_songid='.$share_song_id;
		$sharesongurl = SHARE_ROOT_URL.'/'.$musician_name.'/'.$share_song_id;

		$message = '<html>';
		$message .= '<head>';
			$message .= '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
			$message .= '<title>Untitled Document</title>';
		$message .= '</head>';
		$message .= '<body>';
			$message .= '<table width="800" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial, Helvetica, sans-serif">';
				$message .= '<tr>';
					$message .= '<td>';
						$message .= '<table width="800" height="80" cellspacing="0" cellpadding="0" style="border-bottom:1px solid #8b8b8b;border-top:1px solid #8b8b8b;font-family:Arial, Helvetica, sans-serif">';
							$message .= '<tr>';
								$message .= '<td width="28">&nbsp;</td>';
								$message .= '<td width="203" style="padding:26px 0 17px 0"><img  src="'.ROOT_URL.'/images/logo.jpg" /></td>';
								$message .= '<td width="384">&nbsp;</td>';
							$message .= '</tr>';
						$message .= '</table>';
					$message .= '</td>';
				$message .= '</tr>';
				$message .= '<tr>';
					$message .= '<td width="800">';
						$message .= '<table border="0" cellspacing="0" cellpadding="0" style="color:#6f6e70;font-weight:bold;font-family:Arial, Helvetica, sans-serif; font-size:13px;">';
							$message .= '<tr>';
								$message .= '<td style="padding:28px 0 0 28px;">Hey '.$notifyUserName.' ,</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; width:800px;">'.$musician_name.' has uploaded a new song.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; width:800px;">-</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:5px 0 0 28px"><a href="'.$sharesongurl.'" target="_blank">Listen now!</a></td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td width="28">&nbsp;</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0 0 0 28px; color:#6f6e70;font-weight:bold;font-family:Arial, Helvetica, sans-serif; font-size:13px; width:800px;">Thanks,</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0 0 0 28px; color:#6f6e70;font-weight:bold;font-family:Arial, Helvetica, sans-serif; font-size:13px; width:800px;">DMMCompany&reg; The Musician&#39;s Brand&trade;</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; width:800px;"><a href="http://dmmcompany.com" target="_blank">http://dmmcompany.com</a></td>';
							$message .= '</tr>';
						$message .= '</table>';
					$message .= '</td>';
				$message .= '</tr>';
			$message .= '</table>';          
		$message .= '</body>';
		$message .= '</html>';
		return $message;
	}


	function mailForNotifyUserPaid($dmm_user_name, $to)
	{
		global $notify_pass_payment;
		$headers = "From:DMMCompany <".$notify_pass_payment.">\r\n";
		$headers .= "Content-type: text/html; charset=iso-8859-1" . "\r\n";
		$message = messageForNotifyUserPaid1($dmm_user_name);
		$subject = 'DMMApp Musician ID - FREE Access Granted!';
		mail($to,$subject,$message,$headers);
	}

	function messageForNotifyUserPaid1($dmm_user_name)
	{
		//$message = "Dear clinic,"."<br/>";
		//$message .= "Your appointment has been booked for ".$date." in ".$clinicName." at ".$startTime.". To cancel logon to www.weqaya.ae";
		$message = '<html>';
		$message .= '<head>';
			$message .= '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
			$message .= '<title>Untitled Document</title>';
		$message .= '</head>';
		$message .= '<body>';
			$message .= '<table width="800" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial, Helvetica, sans-serif">';
				$message .= '<tr>';
					$message .= '<td>';
						$message .= '<table width="800" height="80" cellspacing="0" cellpadding="0" style="border-bottom:1px solid #8b8b8b;border-top:1px solid #8b8b8b;font-family:Arial, Helvetica, sans-serif">';
							$message .= '<tr>';
								$message .= '<td width="28">&nbsp;</td>';
								$message .= '<td width="203" style="padding:26px 0 17px 0"><img  src="'.ROOT_URL.'/images/logo.jpg" /></td>';
								$message .= '<td width="384">&nbsp;</td>';
							$message .= '</tr>';
						$message .= '</table>';
					$message .= '</td>';
				$message .= '</tr>';
				$message .= '<tr>';
					$message .= '<td width="800">';
						$message .= '<table border="0" cellspacing="0" cellpadding="0" style="color:#6f6e70;font-weight:normal;font-family:Arial, Helvetica, sans-serif; font-size:13px;">';
							$message .= '<tr>';
								$message .= '<td style="padding:28px 0 0 28px;">Welcome '.$dmm_user_name.'!</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; width:800px;">You have been granted FREE ACCESS to the DMMApp.</br></br>Click your personal Musician ID URL below and start uploading your music!:</td>';
							$message .= '</tr>';
							$message .= '<tr>';
							$message .= '<td>';
							$message .= '<table border="0" cellspacing="0" cellpadding="0" style="color:#6f6e70;font-weight:normal;font-family:Arial, Helvetica, sans-serif; font-size:13px;">';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:18px; width:800px;"><a href="http://dmmcompany.com/'.$dmm_user_name.'" style="color:#00A9EC;">http://dmmcompany.com/'.$dmm_user_name.'</a></td>';
							$message .= '</tr>';
							$message .= '</table>';  
							$message .= '</td>';
							$message .= '</tr>';		
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:21px; width:800px; font-weight:bold; color:red;">Getting to know the DMMCompany&reg; App (Version 8.0.1)</td>';
							$message .= '</tr>';														
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Get your <span style="color:red;">personalized</span> musician URL</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">DMMCompany allows musicians of all genres to expose their talents and creations as they progress, giving basement brilliants equal opportunity to promote themselves alongside established professionals.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Add upto 2 songs for free</td>';
							$message .= '</tr>';
							$message .= '<tr>';
							$message .= '<td>';
							$message .= '<table border="0" cellspacing="0" cellpadding="0" style="color:#6f6e70;font-family:Arial, Helvetica, sans-serif; font-size:13px;">';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px;">Give the world a dose of your sound when you upload 2 songs for free. Once you have exceeded the complimentary 2 song allowance within your personal musicians account, upgrade to the full DMMExperience. UPGRADE details below.</td>';
							$message .= '</tr>';
							$message .= '</table>';  
							$message .= '</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Take advantage of our SharedAudience&trade; model</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">DMMCompany has created a SharedAudience&trade; model that guarantees all good musicians equal exposure.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Track the number of song listens in real time</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">Find out which of your songs people are most excited about by tracking your listens in real-time.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Make it easy for fans to contact you</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">Receive private messages from fans, musicians and potential collaborators, instantly.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Discover the public&#39;s opinion of your work with visible song-specific user comments.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">See what the public has to say about your work; read song specific user comments during song play.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Make it easy for listeners to track you with NotifyMeez&trade;</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">Your fans can be instantly alerted when you post new music. Just post your newest creation when you are ready for the world to hear it, and a DMMAlert will be sent directly to your audience.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Get multiple accounts</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">Create multiple accounts using one email address. This is perfect for musicians who rock under more than one alias.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Billboard image assistance</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">Not all musicians have the resources or ability to design high impact ads. Or maybe you just need assistance converting images specs? DMMCompany provides basic design assistance, including resizing and composition adjustments (only as needed).</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:30px 0 0 28px; font-size:21px; color:red; width:800px;">UPGRADE! Do More With Your DMMApp</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; width:800px;">For $24.99/yr upgrade your personal account for the full DMMExperience.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">+ 20</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">Once you&#39;ve exceeded your free song submissions, upgrade your account to add an additional 20 songs and continue sharing your most creative sounds. Those who are ready to display these stages of their music will find the DMM +20 upgrade, an essential tool in promoting your diversity and most important creations.</br></br>From Established Musicians to Basement Brilliants, an artist is constantly evolving, producing complete catalogs of songs, ideas, experiments and musical masterpieces. Those who are ready to display these stages of their music will find the DMMCompany +20 upgrade an essential tool in promoting the highest level of creativity.</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; font-size:16px; width:800px; font-weight:bold;">Declare Your Strengths! Cross market your talents and services</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0px 0 0 28px; width:800px;">This benefits musicians with small businesses, product endorsers, and any other service or opportunity. Music is our passion and the bridge to endless opportunities. DMMCompany enables full screen promotional advertisements to showcase  talents and services in a new way.</br></br>(Advertisement examples include but are not limited to collaborative project anncouncements, sponsors, product images, endorsement campaigns, tour schedules, appearance announcements, etc.)</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td width="28">&nbsp;</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td width="28">&nbsp;</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0 0 0 28px; color:#6f6e70;font-family:Arial, Helvetica, sans-serif; font-size:13px;">Best Regards,</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:0 0 0 28px; color:#6f6e70;font-family:Arial, Helvetica, sans-serif; font-size:13px; width:800px;">DMMCompany&reg; The Musician&#39;s Brand&trade;</td>';
							$message .= '</tr>';
							$message .= '<tr>';
								$message .= '<td style="padding:20px 0 0 28px; width:800px;"><a href="http://dmmcompany.com" target="_blank">http://dmmcompany.com</a></td>';
							$message .= '</tr>';
						$message .= '</table>';
					$message .= '</td>';
				$message .= '</tr>';
			$message .= '</table>';          
		$message .= '</body>';
		$message .= '</html>';
		return $message;
	}
?>